# Generated by Django 4.2.4 on 2023-08-29 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('date_now', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_model', models.CharField(choices=[('Contract', 'Contract'), ('BuildingSite', 'BuildingSite'), ('Oc', 'OC'), ('Client', 'Client'), ('Supplier', 'Supplier'), ('CajaChica', 'CajaChica'), ('Budget', 'Budget'), ('ProdResource', 'ProdResource'), ('ItemCC', 'ItemCC'), ('ItemResource', 'ItemResource'), ('ProductOc', 'ProductOc')], max_length=20, null=True)),
                ('obj_id', models.IntegerField()),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('date_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasiContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('par', models.BooleanField(default=False)),
                ('mat', models.BooleanField(default=False)),
                ('mau', models.IntegerField(default=0)),
                ('auo', models.BooleanField(default=False)),
                ('proa', models.BooleanField(default=False)),
                ('oc', models.BooleanField(default=False)),
                ('vis', models.BooleanField(default=False)),
                ('uf', models.FloatField()),
                ('sa', models.IntegerField(default=0)),
                ('m2', models.IntegerField(null=True)),
                ('peso', models.IntegerField(null=True)),
                ('ccp', models.BooleanField(default=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=3)),
                ('dec', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBuildingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionContractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('diminutive', models.CharField(max_length=3)),
                ('operacion', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('days', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
