# Generated by Django 4.2.4 on 2023-08-29 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hgi_users', '0001_initial'),
        ('hgi_static', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typepago',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typebudget',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissioncontractuser',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='permissioncontractuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='administrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_administrative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='building_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.buildingsite'),
        ),
        migrations.AddField(
            model_name='contract',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.clasicontract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_users.company'),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='of_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_technique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='preventionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preventionist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.estadocontract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='hgi_static.typecontract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changemanagement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingsite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.client'),
        ),
        migrations.AddField(
            model_name='buildingsite',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_users.company'),
        ),
        migrations.AddField(
            model_name='buildingsite',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
