# Generated by Django 4.2.4 on 2023-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=90, null=True)),
                ('total', models.IntegerField()),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('pre', models.IntegerField()),
                ('prm', models.IntegerField()),
                ('pro', models.IntegerField()),
                ('ccp', models.CharField(max_length=10)),
                ('date_entrance', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateTimeField(auto_now_add=True)),
                ('aut', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('date_now', models.DateTimeField(auto_now_add=True)),
                ('oba', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=70, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('ie', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('sca', models.CharField(blank=True, max_length=25, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField()),
                ('price', models.IntegerField()),
                ('observation', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ing', models.IntegerField(null=True)),
                ('date_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('mat', models.IntegerField(blank=True, null=True)),
                ('afe', models.IntegerField(blank=True, null=True)),
                ('ing', models.IntegerField(blank=True, null=True)),
                ('cpp', models.CharField(blank=True, max_length=15, null=True)),
                ('lso', models.IntegerField(blank=True, null=True)),
                ('doc', models.IntegerField(blank=True, null=True)),
                ('car', models.IntegerField(blank=True, null=True)),
                ('moc', models.IntegerField(blank=True, null=True)),
                ('ant', models.IntegerField(blank=True, null=True)),
                ('date_entrance', models.DateTimeField(auto_now_add=True)),
                ('date_now_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('general_discount', models.IntegerField(default=0)),
                ('observation', models.CharField(default='Sin Observaciones.', max_length=500)),
                ('ref_oc', models.CharField(max_length=20, null=True)),
                ('total', models.IntegerField(default=0)),
                ('dispatch_address', models.CharField(blank=True, max_length=60, null=True)),
                ('ate_oc', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=40, null=True)),
                ('mail2', models.CharField(blank=True, max_length=40, null=True)),
                ('autorization_adm', models.BooleanField(default=False)),
                ('autorization_res', models.BooleanField(default=False)),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('date_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
                ('chargeable', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('operacion', models.IntegerField(blank=True, null=True)),
                ('nco', models.CharField(blank=True, max_length=3, null=True)),
                ('order_1', models.IntegerField(blank=True, null=True)),
                ('order_2', models.IntegerField(blank=True, null=True)),
                ('order_3', models.IntegerField(blank=True, null=True)),
                ('iva', models.BooleanField(default=True)),
                ('ret', models.IntegerField(blank=True, null=True)),
                ('fim', models.CharField(blank=True, max_length=2, null=True)),
                ('lve', models.IntegerField(blank=True, null=True)),
                ('olv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('code', models.IntegerField()),
                ('sub', models.BooleanField(blank=True, null=True)),
                ('rem', models.BooleanField(blank=True, null=True)),
                ('pro', models.IntegerField(blank=True, null=True)),
                ('pag', models.IntegerField(blank=True, null=True)),
                ('arr', models.BooleanField(blank=True, null=True)),
                ('rah', models.BooleanField(blank=True, null=True)),
                ('cch', models.BooleanField(blank=True, null=True)),
                ('man', models.BooleanField(blank=True, null=True)),
                ('ope', models.IntegerField(blank=True, null=True)),
                ('nco', models.CharField(blank=True, max_length=3, null=True)),
                ('col', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('time', models.CharField(blank=True, max_length=5, null=True)),
                ('rfa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
