# Generated by Django 4.2.4 on 2023-08-29 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hgi_users', '0001_initial'),
        ('hgi_static', '0001_initial'),
        ('hgi_sells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_reference', to='hgi_sells.typedocument'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_padre', to='hgi_sells.resource'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='creator_oc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='form_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.typepago'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='state',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='hgi_static.ocstate'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='transmitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transmitter_oc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.typeoc'),
        ),
        migrations.AddField(
            model_name='productoc',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.batch'),
        ),
        migrations.AddField(
            model_name='productoc',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoc',
            name='oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.purchaseorder'),
        ),
        migrations.AddField(
            model_name='productoc',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.resource'),
        ),
        migrations.AddField(
            model_name='productoc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.unitproduct'),
        ),
        migrations.AddField(
            model_name='prodresource',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.batch'),
        ),
        migrations.AddField(
            model_name='prodresource',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.resource'),
        ),
        migrations.AddField(
            model_name='itemresource',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.batch'),
        ),
        migrations.AddField(
            model_name='itemresource',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='itemresource',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.prodresource'),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.batch'),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='caja_chica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.cajachica'),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.resource'),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.supplier'),
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.typedocument'),
        ),
        migrations.AddField(
            model_name='estadocajachica',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cajachica',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_users.company'),
        ),
        migrations.AddField(
            model_name='cajachica',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='cajachica',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cajachica',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.purchaseorder'),
        ),
        migrations.AddField(
            model_name='cajachica',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hgi_sells.estadocajachica'),
        ),
        migrations.AddField(
            model_name='budget',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.typebudget'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contract'),
        ),
        migrations.AddField(
            model_name='batch',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
